package com.example.macchiato.Enums;

public enum NombreMateria {
    INGLES_I,
    FISICA_GENERAL,
    ALGEBRA_I,
    CALCULO_I,
    INTRODUCCION_A_LA_PROGRAMACION,

    INGLES_II,
    ALGEBRA_II,
    CALCULO_II,
    ELEM_DE_PROGRAMACION_Y_ESTRUC_DE_DATOS,
    ARQUITECTURA_DE_COMPUTADORAS_I,
    PROGRAMACION,

    CALCULO_NUMERICO,
    LOGICA,
    ARQUITECTURA_DE_COMPUTADORAS_II,
    TEORIA_DE_GRAFOS,
    ORGANIZACION_Y_METODOS,
    METODOS_Y_TECNICAS_DE_PROGRAMACION,

    PROBABILIDAD_Y_ESTADISTICA,
    TALLER_DE_PROGRAMACION_EN_BAJO_NIVEL,
    BASE_DE_DATOS_I,
    SISTEMAS_DE_INFORMACION_I,
    PROGRAMACION_FUNCIONAL,
    ALGORITMOS_AVANZADOS,

    BASE_DE_DATOS_II,
    TALLER_DE_SISTEMAS_OPERATIVOS,
    SISTEMAS_DE_INFORMACION_II,
    TEORIA_DE_AUTOMATAS_Y_LENG_FORMALES,
    GRAFICACION_POR_COMPUTADORA,
    INTELIGENCIA_ARTIFICIAL_I,

    INGENIERIA_DE_SOFTWARE,
    REDES_DE_COMPUTADORAS,
    ESTRUCTURA_Y_SEMANTICA_DE_LENGUAJES_DE_PROGRAMACION,
    TALLER_DE_BASE_DE_DATOS,
    INTELIGENCIA_ARTIFICIAL_II,
    PROGRAMACION_WEB,

    SIMULACION_DE_SISTEMAS,
    TALLER_DE_INGENIERIA_DE_SOFTWARE,
    ARQUITECTURA_DE_SOFTWARE,
    TELEFONIA_IP,
    INTERACCION_HUMANO_COMPUTADOR,
    TECNOLOGIA_REDES_AVANZADAS,

    APLICACION_DE_SISTEMAS_OPERATIVOS,
    EVALUACION_Y_AUDITORIA_DE_SISTEMAS,
    TALLER_DE_GRADO_I,

    DATA_WAREHOUSE,
    DISE¥O_DE_COMPILADORES,
    WEB_SEMANTICAS,
    ROBOTICA,
    PROGRAMACION_MOVIL,
    AGENTES_INTELIGENTES,
    APLICACIONES_WEB_AVANZADAS,
    SEGURIDAD_DE_SISTEMAS,
    TALLER_DE_GRADO_II
}
